import {
    ArgumentsHost,
    Catch,
    ExceptionFilter,
    HttpException,
    BadRequestException,
    Logger,
    NotFoundException,
    ConflictException,
} from "@nestjs/common";
import { RpcException } from "@nestjs/microservices";
import { throwError } from "rxjs";

@Catch(RpcException, BadRequestException, NotFoundException, ConflictException)
export class GlobalRpcExceptionFilter implements ExceptionFilter {
    private readonly logger = new Logger(GlobalRpcExceptionFilter.name);

    catch(
        exception:
            | RpcException
            | BadRequestException
            | NotFoundException
            | ConflictException,
        host: ArgumentsHost
    ) {
        let status = 400;
        let message = "Erreur inconnue.";

        if (exception instanceof RpcException) {
            // âœ… Si l'exception est une `RpcException`, on rÃ©cupÃ¨re son message
            message = exception.getError() as string;
        } else {
            // âœ… Si l'exception est une `BadRequestException`, on rÃ©cupÃ¨re la rÃ©ponse
            const response = exception.getResponse();
            message =
                typeof response === "string" ? response : response["message"];
            status = exception.getStatus();
        }

        this.logger.warn(`ðŸ“Œ RPC Error Captured: ${message}`);
        return throwError(
            () => new RpcException({ statusCode: status, message })
        );
    }
}
